// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PRN232_PE_FA25_NguyenKhanhTin.Data;

#nullable disable

namespace PRN232_PE_FA25_NguyenKhanhTin.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251112170719_InitPosts")]
    partial class InitPosts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PRN232_PE_FA25_NguyenKhanhTin.Models.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 11, 12, 17, 7, 18, 609, DateTimeKind.Utc).AddTicks(3604),
                            Description = "Minimal API + HTML",
                            Name = "Hello PRN232"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 11, 12, 17, 7, 18, 609, DateTimeKind.Utc).AddTicks(3605),
                            Description = "Connected to Supabase/Postgres",
                            ImageUrl = "https://picsum.photos/seed/p1/400/240",
                            Name = "Deploy Render"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 11, 12, 17, 7, 18, 609, DateTimeKind.Utc).AddTicks(3606),
                            Description = "A→Z / Z→A + search by name",
                            ImageUrl = "https://picsum.photos/seed/p2/400/240",
                            Name = "Search & Sort"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
